apiVersion: v1
name: kafka-streams-chart
version: 0.1.0
description: An example chart for Kafka Streams
keywords:
  - kafka
  - kafka streams
home: https://kafka-streams-book.com
sources:
  - https://github.com/mitch-seymour/mastering-kafka-streams-and-ksqldb
maintainers: # (optional)
  - name: Mitch Seymour
    email: mitchseymour@gmail.com
    url: https://mitchseymour.com/
engine: gotpl
#TODO
#icon: A URL to an SVG or PNG image to be used as an icon (optional).
appVersion: 0.1.0
deprecated: false
tillerVersion: ">2.0.0"
