apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: grafana
  name: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: grafana
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: grafana
        app: grafana
    spec:
      containers:
      - image: {{ .Values.images.grafana }}
        imagePullPolicy: ""
        name: grafana
        ports:
        - containerPort: 3000
        resources: {}
        #volumeMounts:
        #- mountPath: /var/lib/grafana
        #  name: grafana-claim0
      hostname: grafana
      restartPolicy: Always
      serviceAccountName: ""
      #volumes:
      #- name: grafana-claim0
      #  persistentVolumeClaim:
      #    claimName: grafana-claim0
status: {}
