---
apiVersion: v1
kind: ConfigMap
metadata:
  name: create-kafka-topics
  namespace: {{ $.Release.Namespace }}
data:
  create-topics.sh: |-
    echo "Waiting for Kafka to come online..."

    cub kafka-ready -b broker:29092 1 20

    echo "Kafka is online. Creating topics"

    {{ range $index, $topic := .Values.topics }}
    kafka-topics \
      --bootstrap-server broker:29092 \
      --topic {{ $topic.name }} \
      --replication-factor 1 \
      --partitions {{ $topic.partitions }} \
      --create
    {{- end }}